add mythsmolt

diff --git a/mythplugins/configure b/mythplugins/configure
--- a/mythplugins/configure
+++ b/mythplugins/configure
@@ -105,6 +105,7 @@ game
 music
 netvision
 news
+smolt
 video
 weather
 zoneminder
@@ -188,7 +189,10 @@ MythZoneMinder related options:
   --enable-mythzoneminder  build the mythzoneminder plugin [$zoneminder]
 
 MythNetvision related options:
-  --enable-mythnetvision      build the mythnetvision plugin [$netvision]
+  --enable-mythnetvision   build the mythnetvision plugin [$netvision]
+
+MythSmolt related options:
+  --enable-mythsmolt       build the mythsmolt plugin [$smolt]
 
 EOF
 exit 0
@@ -442,6 +446,16 @@ if ! disabled netvision; then
     disabled netvision && echo "Disabling MythNetvision due to missing dependencies."
 fi
 
+if ! disabled smolt; then
+    disable_smolt() {
+        msg="$1"
+        echo "MythSmolt requires the $msg"
+        disable smolt
+    }
+    # check for deps here
+    disabled smolt && echo "Disabling MythSmolt due to missing dependencies."
+fi
+
 if ! disabled weather; then
     check_pl_lib(){
         log check_pl_lib "$@"
@@ -675,6 +689,13 @@ if test "$netvision" = "yes" ; then
   echo "SUBDIRS += mythnetvision" >> ./config.pro
 else
   echo "        MythNetvision  plugin will not be built"
+fi
+
+if test "$smolt" = "yes" ; then
+  echo "        MythSmolt      plugin will be built"
+  echo "SUBDIRS += mythsmolt" >> ./config.pro
+else
+  echo "        MythSmolt      plugin will not be built"
 fi
 
 ###########################################################
